### ISSUE TITLE
Firefox v79.0 fullscreen stopped working

### ISSUE THREAD

**Issue by keybreak** [devkral/lightsonplus#29]
:disappointed:

Any ideas?

**Comment by g--o** [comment]
me too
i'm not sure but i think pgrep stopped detecting firefox for me

**Comment by devkral** [comment]
why would anyone remove his trademarked name from the process name? Strange guys at mozilla but fixed.

**Comment by keybreak** [comment]
Yeah, indeed that's weird...

Thx! :+1:
